// This file is generated by scripts/generate-vitepress-labs.mjs. Do not edit directly.
import type { DefaultTheme } from 'vitepress'

export const labsSidebarItems: DefaultTheme.SidebarItem[] = [
  {"text":"Agent Service Introduction","link":"/labs/agent-service-introduction"},
  {"text":"Lab 00 Workshop setup and access verification","link":"/.generated/lab-steps/agent-service-introduction/00-setup"},
  {"text":"Lab 01 Hosted agents with framework-orchestrated ReAct","link":"/.generated/lab-steps/agent-service-introduction/01-hosted-agents"},
  {"text":"Lab 02 Prompt-based agents with tool calling","link":"/.generated/lab-steps/agent-service-introduction/02-prompt-based-agents"},
  {"text":"Lab 03 Multi-agent as tools","link":"/.generated/lab-steps/agent-service-introduction/03-multi-agent-as-tools"},
  {"text":"Lab 04 Microsoft Agent Framework in Python","link":"/.generated/lab-steps/agent-service-introduction/04-agent-framework-python"},
  {"text":"Lab 05 Foundry IQ multi-source retrieval","link":"/.generated/lab-steps/agent-service-introduction/05-foundry-iq"},
  {"text":"Lab 06 Foundry Toolkit for VS Code tasks","link":"/.generated/lab-steps/agent-service-introduction/06-foundry-toolkit-vscode"},
  {"text":"Lab 07 Foundry Toolboxes (optional)","link":"/.generated/lab-steps/agent-service-introduction/07-foundry-toolboxes"},
  {"text":"Lab 08 Agent ID and publishing","link":"/.generated/lab-steps/agent-service-introduction/08-agent-id-and-publishing"},
]
