name: Continuous Delivery

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - infra/**
      - labs/**
      - shared/**
      - azure.yaml
      - .github/workflows/continuous-delivery.yml
      - .github/workflows/lint-and-publish-bicep.yml
      - .github/workflows/e2e-test.yml
      - .github/workflows/validate-infrastructure.yml
      - .github/workflows/provision-infrastructure.yml
      - .github/workflows/delete-infrastructure.yml
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  checks: write

concurrency:
  group: continuous-delivery-${{ github.ref }}
  cancel-in-progress: false

jobs:
  set-build-variables:
    name: Set Build Variables
    runs-on: ubuntu-latest
    outputs:
      BUILD_VERSION: ${{ steps.build-version.outputs.BUILD_VERSION }}
    steps:
      - name: Set build version
        id: build-version
        run: echo "BUILD_VERSION=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

  lint-and-publish-bicep:
    name: Lint and Publish Bicep
    needs:
      - set-build-variables
    uses: ./.github/workflows/lint-and-publish-bicep.yml
    permissions:
      contents: read
      pull-requests: write

  e2e-test-v1:
    name: E2E Test
    needs:
      - set-build-variables
      - lint-and-publish-bicep
    uses: ./.github/workflows/e2e-test.yml
    with:
      ENVIRONMENT: test
      BUILD_VERSION: ${{ needs.set-build-variables.outputs.BUILD_VERSION }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION || 'eastus2' }}
      AZURE_ENV_NAME: ${{ format('fdyaw-{0}', github.run_id) }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
